# coding: utf-8

"""
    Mobile API

    All decimal values are accepted and returned with 2 decimal place precision, e.g., 150.21. All date fields are sent in ISO 8601 format YYYY-MM-DD, e.g., 2016-11-30.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import viventor_api_mobile
from viventor_api_mobile.api.user_controller_api import UserControllerApi  # noqa: E501
from viventor_api_mobile.rest import ApiException


class TestUserControllerApi(unittest.TestCase):
    """UserControllerApi unit test stubs"""

    def setUp(self):
        self.api = viventor_api_mobile.api.user_controller_api.UserControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_account_user_settings_using_get(self):
        """Test case for get_account_user_settings_using_get

        getAccountUserSettings  # noqa: E501
        """
        pass

    def test_get_bank_accounts_using_get(self):
        """Test case for get_bank_accounts_using_get

        getBankAccounts  # noqa: E501
        """
        pass

    def test_save_account_user_settings_using_post(self):
        """Test case for save_account_user_settings_using_post

        saveAccountUserSettings  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
