# coding: utf-8

"""
    Mobile API

    All decimal values are accepted and returned with 2 decimal place precision, e.g., 150.21. All date fields are sent in ISO 8601 format YYYY-MM-DD, e.g., 2016-11-30.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import viventor_api_mobile
from viventor_api_mobile.api.legacy_password_controller_api import LegacyPasswordControllerApi  # noqa: E501
from viventor_api_mobile.rest import ApiException


class TestLegacyPasswordControllerApi(unittest.TestCase):
    """LegacyPasswordControllerApi unit test stubs"""

    def setUp(self):
        self.api = viventor_api_mobile.api.legacy_password_controller_api.LegacyPasswordControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_change_password_using_post1(self):
        """Test case for change_password_using_post1

        changePassword  # noqa: E501
        """
        pass

    def test_confirm_password_reset_using_post(self):
        """Test case for confirm_password_reset_using_post

        confirmPasswordReset  # noqa: E501
        """
        pass

    def test_request_password_reset_using_post(self):
        """Test case for request_password_reset_using_post

        requestPasswordReset  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
