# coding: utf-8

"""
    Mobile API

    All decimal values are accepted and returned with 2 decimal place precision, e.g., 150.21. All date fields are sent in ISO 8601 format YYYY-MM-DD, e.g., 2016-11-30.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import api_mobile
from api_mobile.models.generic import Generic  # noqa: E501
from api_mobile.rest import ApiException


class TestGeneric(unittest.TestCase):
    """Generic unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeneric(self):
        """Test Generic"""
        # FIXME: construct object with mandatory attributes with example values
        # model = viventor_api_mobile.models.generic.Generic()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
