# coding: utf-8

"""
    Mobile API

    All decimal values are accepted and returned with 2 decimal place precision, e.g., 150.21. All date fields are sent in ISO 8601 format YYYY-MM-DD, e.g., 2016-11-30.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class GeneralInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'countries_list': 'dict(str, int)',
        'originators_list': 'dict(str, int)'
    }

    attribute_map = {
        'countries_list': 'countriesList',
        'originators_list': 'originatorsList'
    }

    def __init__(self, countries_list=None, originators_list=None):  # noqa: E501
        """GeneralInfo - a model defined in Swagger"""  # noqa: E501

        self._countries_list = None
        self._originators_list = None
        self.discriminator = None

        if countries_list is not None:
            self.countries_list = countries_list
        if originators_list is not None:
            self.originators_list = originators_list

    @property
    def countries_list(self):
        """Gets the countries_list of this GeneralInfo.  # noqa: E501


        :return: The countries_list of this GeneralInfo.  # noqa: E501
        :rtype: dict(str, int)
        """
        return self._countries_list

    @countries_list.setter
    def countries_list(self, countries_list):
        """Sets the countries_list of this GeneralInfo.


        :param countries_list: The countries_list of this GeneralInfo.  # noqa: E501
        :type: dict(str, int)
        """

        self._countries_list = countries_list

    @property
    def originators_list(self):
        """Gets the originators_list of this GeneralInfo.  # noqa: E501


        :return: The originators_list of this GeneralInfo.  # noqa: E501
        :rtype: dict(str, int)
        """
        return self._originators_list

    @originators_list.setter
    def originators_list(self, originators_list):
        """Sets the originators_list of this GeneralInfo.


        :param originators_list: The originators_list of this GeneralInfo.  # noqa: E501
        :type: dict(str, int)
        """

        self._originators_list = originators_list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GeneralInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GeneralInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
