# coding: utf-8

"""
    Mobile API

    All decimal values are accepted and returned with 2 decimal place precision, e.g., 150.21. All date fields are sent in ISO 8601 format YYYY-MM-DD, e.g., 2016-11-30.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SecondaryInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'amount': 'float',
        'bank_guarantee': 'bool',
        'bonus_percentage': 'float',
        'buyback': 'bool',
        'company': 'str',
        'extended': 'bool',
        'guarantee': 'bool',
        'ils_id': 'int',
        'ilsa_id': 'int',
        'ilsa_status': 'int',
        'interest': 'float',
        'investment_enabled': 'bool',
        'investor': 'int',
        'itv': 'float',
        'last_modification': 'datetime',
        'loan_payment_enabled': 'bool',
        'loan_status': 'int',
        'lr_id': 'int',
        'outstanding': 'float',
        'payment_guarantee': 'bool',
        'price': 'float',
        'remaining_term': 'int',
        't_presta_key': 'int',
        'term': 'int'
    }

    attribute_map = {
        'amount': 'amount',
        'bank_guarantee': 'bank_guarantee',
        'bonus_percentage': 'bonus_percentage',
        'buyback': 'buyback',
        'company': 'company',
        'extended': 'extended',
        'guarantee': 'guarantee',
        'ils_id': 'ilsId',
        'ilsa_id': 'ilsaId',
        'ilsa_status': 'ilsaStatus',
        'interest': 'interest',
        'investment_enabled': 'investment_enabled',
        'investor': 'investor',
        'itv': 'itv',
        'last_modification': 'last_modification',
        'loan_payment_enabled': 'loan_payment_enabled',
        'loan_status': 'loan_status',
        'lr_id': 'lrId',
        'outstanding': 'outstanding',
        'payment_guarantee': 'payment_guarantee',
        'price': 'price',
        'remaining_term': 'remaining_term',
        't_presta_key': 't_presta_key',
        'term': 'term'
    }

    def __init__(self, amount=None, bank_guarantee=None, bonus_percentage=None, buyback=None, company=None, extended=None, guarantee=None, ils_id=None, ilsa_id=None, ilsa_status=None, interest=None, investment_enabled=None, investor=None, itv=None, last_modification=None, loan_payment_enabled=None, loan_status=None, lr_id=None, outstanding=None, payment_guarantee=None, price=None, remaining_term=None, t_presta_key=None, term=None):  # noqa: E501
        """SecondaryInfo - a model defined in Swagger"""  # noqa: E501

        self._amount = None
        self._bank_guarantee = None
        self._bonus_percentage = None
        self._buyback = None
        self._company = None
        self._extended = None
        self._guarantee = None
        self._ils_id = None
        self._ilsa_id = None
        self._ilsa_status = None
        self._interest = None
        self._investment_enabled = None
        self._investor = None
        self._itv = None
        self._last_modification = None
        self._loan_payment_enabled = None
        self._loan_status = None
        self._lr_id = None
        self._outstanding = None
        self._payment_guarantee = None
        self._price = None
        self._remaining_term = None
        self._t_presta_key = None
        self._term = None
        self.discriminator = None

        if amount is not None:
            self.amount = amount
        if bank_guarantee is not None:
            self.bank_guarantee = bank_guarantee
        if bonus_percentage is not None:
            self.bonus_percentage = bonus_percentage
        if buyback is not None:
            self.buyback = buyback
        if company is not None:
            self.company = company
        if extended is not None:
            self.extended = extended
        if guarantee is not None:
            self.guarantee = guarantee
        if ils_id is not None:
            self.ils_id = ils_id
        if ilsa_id is not None:
            self.ilsa_id = ilsa_id
        if ilsa_status is not None:
            self.ilsa_status = ilsa_status
        if interest is not None:
            self.interest = interest
        if investment_enabled is not None:
            self.investment_enabled = investment_enabled
        if investor is not None:
            self.investor = investor
        if itv is not None:
            self.itv = itv
        if last_modification is not None:
            self.last_modification = last_modification
        if loan_payment_enabled is not None:
            self.loan_payment_enabled = loan_payment_enabled
        if loan_status is not None:
            self.loan_status = loan_status
        if lr_id is not None:
            self.lr_id = lr_id
        if outstanding is not None:
            self.outstanding = outstanding
        if payment_guarantee is not None:
            self.payment_guarantee = payment_guarantee
        if price is not None:
            self.price = price
        if remaining_term is not None:
            self.remaining_term = remaining_term
        if t_presta_key is not None:
            self.t_presta_key = t_presta_key
        if term is not None:
            self.term = term

    @property
    def amount(self):
        """Gets the amount of this SecondaryInfo.  # noqa: E501


        :return: The amount of this SecondaryInfo.  # noqa: E501
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this SecondaryInfo.


        :param amount: The amount of this SecondaryInfo.  # noqa: E501
        :type: float
        """

        self._amount = amount

    @property
    def bank_guarantee(self):
        """Gets the bank_guarantee of this SecondaryInfo.  # noqa: E501


        :return: The bank_guarantee of this SecondaryInfo.  # noqa: E501
        :rtype: bool
        """
        return self._bank_guarantee

    @bank_guarantee.setter
    def bank_guarantee(self, bank_guarantee):
        """Sets the bank_guarantee of this SecondaryInfo.


        :param bank_guarantee: The bank_guarantee of this SecondaryInfo.  # noqa: E501
        :type: bool
        """

        self._bank_guarantee = bank_guarantee

    @property
    def bonus_percentage(self):
        """Gets the bonus_percentage of this SecondaryInfo.  # noqa: E501


        :return: The bonus_percentage of this SecondaryInfo.  # noqa: E501
        :rtype: float
        """
        return self._bonus_percentage

    @bonus_percentage.setter
    def bonus_percentage(self, bonus_percentage):
        """Sets the bonus_percentage of this SecondaryInfo.


        :param bonus_percentage: The bonus_percentage of this SecondaryInfo.  # noqa: E501
        :type: float
        """

        self._bonus_percentage = bonus_percentage

    @property
    def buyback(self):
        """Gets the buyback of this SecondaryInfo.  # noqa: E501


        :return: The buyback of this SecondaryInfo.  # noqa: E501
        :rtype: bool
        """
        return self._buyback

    @buyback.setter
    def buyback(self, buyback):
        """Sets the buyback of this SecondaryInfo.


        :param buyback: The buyback of this SecondaryInfo.  # noqa: E501
        :type: bool
        """

        self._buyback = buyback

    @property
    def company(self):
        """Gets the company of this SecondaryInfo.  # noqa: E501


        :return: The company of this SecondaryInfo.  # noqa: E501
        :rtype: str
        """
        return self._company

    @company.setter
    def company(self, company):
        """Sets the company of this SecondaryInfo.


        :param company: The company of this SecondaryInfo.  # noqa: E501
        :type: str
        """

        self._company = company

    @property
    def extended(self):
        """Gets the extended of this SecondaryInfo.  # noqa: E501


        :return: The extended of this SecondaryInfo.  # noqa: E501
        :rtype: bool
        """
        return self._extended

    @extended.setter
    def extended(self, extended):
        """Sets the extended of this SecondaryInfo.


        :param extended: The extended of this SecondaryInfo.  # noqa: E501
        :type: bool
        """

        self._extended = extended

    @property
    def guarantee(self):
        """Gets the guarantee of this SecondaryInfo.  # noqa: E501


        :return: The guarantee of this SecondaryInfo.  # noqa: E501
        :rtype: bool
        """
        return self._guarantee

    @guarantee.setter
    def guarantee(self, guarantee):
        """Sets the guarantee of this SecondaryInfo.


        :param guarantee: The guarantee of this SecondaryInfo.  # noqa: E501
        :type: bool
        """

        self._guarantee = guarantee

    @property
    def ils_id(self):
        """Gets the ils_id of this SecondaryInfo.  # noqa: E501


        :return: The ils_id of this SecondaryInfo.  # noqa: E501
        :rtype: int
        """
        return self._ils_id

    @ils_id.setter
    def ils_id(self, ils_id):
        """Sets the ils_id of this SecondaryInfo.


        :param ils_id: The ils_id of this SecondaryInfo.  # noqa: E501
        :type: int
        """

        self._ils_id = ils_id

    @property
    def ilsa_id(self):
        """Gets the ilsa_id of this SecondaryInfo.  # noqa: E501


        :return: The ilsa_id of this SecondaryInfo.  # noqa: E501
        :rtype: int
        """
        return self._ilsa_id

    @ilsa_id.setter
    def ilsa_id(self, ilsa_id):
        """Sets the ilsa_id of this SecondaryInfo.


        :param ilsa_id: The ilsa_id of this SecondaryInfo.  # noqa: E501
        :type: int
        """

        self._ilsa_id = ilsa_id

    @property
    def ilsa_status(self):
        """Gets the ilsa_status of this SecondaryInfo.  # noqa: E501


        :return: The ilsa_status of this SecondaryInfo.  # noqa: E501
        :rtype: int
        """
        return self._ilsa_status

    @ilsa_status.setter
    def ilsa_status(self, ilsa_status):
        """Sets the ilsa_status of this SecondaryInfo.


        :param ilsa_status: The ilsa_status of this SecondaryInfo.  # noqa: E501
        :type: int
        """

        self._ilsa_status = ilsa_status

    @property
    def interest(self):
        """Gets the interest of this SecondaryInfo.  # noqa: E501


        :return: The interest of this SecondaryInfo.  # noqa: E501
        :rtype: float
        """
        return self._interest

    @interest.setter
    def interest(self, interest):
        """Sets the interest of this SecondaryInfo.


        :param interest: The interest of this SecondaryInfo.  # noqa: E501
        :type: float
        """

        self._interest = interest

    @property
    def investment_enabled(self):
        """Gets the investment_enabled of this SecondaryInfo.  # noqa: E501


        :return: The investment_enabled of this SecondaryInfo.  # noqa: E501
        :rtype: bool
        """
        return self._investment_enabled

    @investment_enabled.setter
    def investment_enabled(self, investment_enabled):
        """Sets the investment_enabled of this SecondaryInfo.


        :param investment_enabled: The investment_enabled of this SecondaryInfo.  # noqa: E501
        :type: bool
        """

        self._investment_enabled = investment_enabled

    @property
    def investor(self):
        """Gets the investor of this SecondaryInfo.  # noqa: E501


        :return: The investor of this SecondaryInfo.  # noqa: E501
        :rtype: int
        """
        return self._investor

    @investor.setter
    def investor(self, investor):
        """Sets the investor of this SecondaryInfo.


        :param investor: The investor of this SecondaryInfo.  # noqa: E501
        :type: int
        """

        self._investor = investor

    @property
    def itv(self):
        """Gets the itv of this SecondaryInfo.  # noqa: E501


        :return: The itv of this SecondaryInfo.  # noqa: E501
        :rtype: float
        """
        return self._itv

    @itv.setter
    def itv(self, itv):
        """Sets the itv of this SecondaryInfo.


        :param itv: The itv of this SecondaryInfo.  # noqa: E501
        :type: float
        """

        self._itv = itv

    @property
    def last_modification(self):
        """Gets the last_modification of this SecondaryInfo.  # noqa: E501


        :return: The last_modification of this SecondaryInfo.  # noqa: E501
        :rtype: datetime
        """
        return self._last_modification

    @last_modification.setter
    def last_modification(self, last_modification):
        """Sets the last_modification of this SecondaryInfo.


        :param last_modification: The last_modification of this SecondaryInfo.  # noqa: E501
        :type: datetime
        """

        self._last_modification = last_modification

    @property
    def loan_payment_enabled(self):
        """Gets the loan_payment_enabled of this SecondaryInfo.  # noqa: E501


        :return: The loan_payment_enabled of this SecondaryInfo.  # noqa: E501
        :rtype: bool
        """
        return self._loan_payment_enabled

    @loan_payment_enabled.setter
    def loan_payment_enabled(self, loan_payment_enabled):
        """Sets the loan_payment_enabled of this SecondaryInfo.


        :param loan_payment_enabled: The loan_payment_enabled of this SecondaryInfo.  # noqa: E501
        :type: bool
        """

        self._loan_payment_enabled = loan_payment_enabled

    @property
    def loan_status(self):
        """Gets the loan_status of this SecondaryInfo.  # noqa: E501


        :return: The loan_status of this SecondaryInfo.  # noqa: E501
        :rtype: int
        """
        return self._loan_status

    @loan_status.setter
    def loan_status(self, loan_status):
        """Sets the loan_status of this SecondaryInfo.


        :param loan_status: The loan_status of this SecondaryInfo.  # noqa: E501
        :type: int
        """

        self._loan_status = loan_status

    @property
    def lr_id(self):
        """Gets the lr_id of this SecondaryInfo.  # noqa: E501


        :return: The lr_id of this SecondaryInfo.  # noqa: E501
        :rtype: int
        """
        return self._lr_id

    @lr_id.setter
    def lr_id(self, lr_id):
        """Sets the lr_id of this SecondaryInfo.


        :param lr_id: The lr_id of this SecondaryInfo.  # noqa: E501
        :type: int
        """

        self._lr_id = lr_id

    @property
    def outstanding(self):
        """Gets the outstanding of this SecondaryInfo.  # noqa: E501


        :return: The outstanding of this SecondaryInfo.  # noqa: E501
        :rtype: float
        """
        return self._outstanding

    @outstanding.setter
    def outstanding(self, outstanding):
        """Sets the outstanding of this SecondaryInfo.


        :param outstanding: The outstanding of this SecondaryInfo.  # noqa: E501
        :type: float
        """

        self._outstanding = outstanding

    @property
    def payment_guarantee(self):
        """Gets the payment_guarantee of this SecondaryInfo.  # noqa: E501


        :return: The payment_guarantee of this SecondaryInfo.  # noqa: E501
        :rtype: bool
        """
        return self._payment_guarantee

    @payment_guarantee.setter
    def payment_guarantee(self, payment_guarantee):
        """Sets the payment_guarantee of this SecondaryInfo.


        :param payment_guarantee: The payment_guarantee of this SecondaryInfo.  # noqa: E501
        :type: bool
        """

        self._payment_guarantee = payment_guarantee

    @property
    def price(self):
        """Gets the price of this SecondaryInfo.  # noqa: E501


        :return: The price of this SecondaryInfo.  # noqa: E501
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this SecondaryInfo.


        :param price: The price of this SecondaryInfo.  # noqa: E501
        :type: float
        """

        self._price = price

    @property
    def remaining_term(self):
        """Gets the remaining_term of this SecondaryInfo.  # noqa: E501


        :return: The remaining_term of this SecondaryInfo.  # noqa: E501
        :rtype: int
        """
        return self._remaining_term

    @remaining_term.setter
    def remaining_term(self, remaining_term):
        """Sets the remaining_term of this SecondaryInfo.


        :param remaining_term: The remaining_term of this SecondaryInfo.  # noqa: E501
        :type: int
        """

        self._remaining_term = remaining_term

    @property
    def t_presta_key(self):
        """Gets the t_presta_key of this SecondaryInfo.  # noqa: E501


        :return: The t_presta_key of this SecondaryInfo.  # noqa: E501
        :rtype: int
        """
        return self._t_presta_key

    @t_presta_key.setter
    def t_presta_key(self, t_presta_key):
        """Sets the t_presta_key of this SecondaryInfo.


        :param t_presta_key: The t_presta_key of this SecondaryInfo.  # noqa: E501
        :type: int
        """

        self._t_presta_key = t_presta_key

    @property
    def term(self):
        """Gets the term of this SecondaryInfo.  # noqa: E501


        :return: The term of this SecondaryInfo.  # noqa: E501
        :rtype: int
        """
        return self._term

    @term.setter
    def term(self, term):
        """Sets the term of this SecondaryInfo.


        :param term: The term of this SecondaryInfo.  # noqa: E501
        :type: int
        """

        self._term = term

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SecondaryInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SecondaryInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
