# coding: utf-8

"""
    Mobile API

    All decimal values are accepted and returned with 2 decimal place precision, e.g., 150.21. All date fields are sent in ISO 8601 format YYYY-MM-DD, e.g., 2016-11-30.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Company(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'business_sector': 'str',
        'country': 'str',
        'date_of_incorporation': 'date',
        'description': 'str'
    }

    attribute_map = {
        'business_sector': 'business_sector',
        'country': 'country',
        'date_of_incorporation': 'date_of_incorporation',
        'description': 'description'
    }

    def __init__(self, business_sector=None, country=None, date_of_incorporation=None, description=None):  # noqa: E501
        """Company - a model defined in Swagger"""  # noqa: E501

        self._business_sector = None
        self._country = None
        self._date_of_incorporation = None
        self._description = None
        self.discriminator = None

        if business_sector is not None:
            self.business_sector = business_sector
        if country is not None:
            self.country = country
        if date_of_incorporation is not None:
            self.date_of_incorporation = date_of_incorporation
        if description is not None:
            self.description = description

    @property
    def business_sector(self):
        """Gets the business_sector of this Company.  # noqa: E501


        :return: The business_sector of this Company.  # noqa: E501
        :rtype: str
        """
        return self._business_sector

    @business_sector.setter
    def business_sector(self, business_sector):
        """Sets the business_sector of this Company.


        :param business_sector: The business_sector of this Company.  # noqa: E501
        :type: str
        """

        self._business_sector = business_sector

    @property
    def country(self):
        """Gets the country of this Company.  # noqa: E501


        :return: The country of this Company.  # noqa: E501
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country):
        """Sets the country of this Company.


        :param country: The country of this Company.  # noqa: E501
        :type: str
        """

        self._country = country

    @property
    def date_of_incorporation(self):
        """Gets the date_of_incorporation of this Company.  # noqa: E501


        :return: The date_of_incorporation of this Company.  # noqa: E501
        :rtype: date
        """
        return self._date_of_incorporation

    @date_of_incorporation.setter
    def date_of_incorporation(self, date_of_incorporation):
        """Sets the date_of_incorporation of this Company.


        :param date_of_incorporation: The date_of_incorporation of this Company.  # noqa: E501
        :type: date
        """

        self._date_of_incorporation = date_of_incorporation

    @property
    def description(self):
        """Gets the description of this Company.  # noqa: E501


        :return: The description of this Company.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Company.


        :param description: The description of this Company.  # noqa: E501
        :type: str
        """

        self._description = description

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Company, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Company):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
