# coding: utf-8

"""
    Mobile API

    All decimal values are accepted and returned with 2 decimal place precision, e.g., 150.21. All date fields are sent in ISO 8601 format YYYY-MM-DD, e.g., 2016-11-30.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Invoice(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'advance_rate': 'float',
        'full_amount': 'float'
    }

    attribute_map = {
        'advance_rate': 'advance_rate',
        'full_amount': 'full_amount'
    }

    def __init__(self, advance_rate=None, full_amount=None):  # noqa: E501
        """Invoice - a model defined in Swagger"""  # noqa: E501

        self._advance_rate = None
        self._full_amount = None
        self.discriminator = None

        if advance_rate is not None:
            self.advance_rate = advance_rate
        if full_amount is not None:
            self.full_amount = full_amount

    @property
    def advance_rate(self):
        """Gets the advance_rate of this Invoice.  # noqa: E501


        :return: The advance_rate of this Invoice.  # noqa: E501
        :rtype: float
        """
        return self._advance_rate

    @advance_rate.setter
    def advance_rate(self, advance_rate):
        """Sets the advance_rate of this Invoice.


        :param advance_rate: The advance_rate of this Invoice.  # noqa: E501
        :type: float
        """

        self._advance_rate = advance_rate

    @property
    def full_amount(self):
        """Gets the full_amount of this Invoice.  # noqa: E501


        :return: The full_amount of this Invoice.  # noqa: E501
        :rtype: float
        """
        return self._full_amount

    @full_amount.setter
    def full_amount(self, full_amount):
        """Sets the full_amount of this Invoice.


        :param full_amount: The full_amount of this Invoice.  # noqa: E501
        :type: float
        """

        self._full_amount = full_amount

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Invoice, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Invoice):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
