# coding: utf-8

"""
    Mobile API

    All decimal values are accepted and returned with 2 decimal place precision, e.g., 150.21. All date fields are sent in ISO 8601 format YYYY-MM-DD, e.g., 2016-11-30.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class UserInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'email': 'str',
        'first_login': 'int',
        'funds_available': 'float',
        'id': 'int',
        'investor_id': 'int',
        'language': 'str',
        'name': 'str',
        'surname': 'str'
    }

    attribute_map = {
        'email': 'email',
        'first_login': 'first_login',
        'funds_available': 'funds_available',
        'id': 'id',
        'investor_id': 'investor_id',
        'language': 'language',
        'name': 'name',
        'surname': 'surname'
    }

    def __init__(self, email=None, first_login=None, funds_available=None, id=None, investor_id=None, language=None, name=None, surname=None):  # noqa: E501
        """UserInfo - a model defined in Swagger"""  # noqa: E501

        self._email = None
        self._first_login = None
        self._funds_available = None
        self._id = None
        self._investor_id = None
        self._language = None
        self._name = None
        self._surname = None
        self.discriminator = None

        if email is not None:
            self.email = email
        if first_login is not None:
            self.first_login = first_login
        if funds_available is not None:
            self.funds_available = funds_available
        if id is not None:
            self.id = id
        if investor_id is not None:
            self.investor_id = investor_id
        if language is not None:
            self.language = language
        if name is not None:
            self.name = name
        if surname is not None:
            self.surname = surname

    @property
    def email(self):
        """Gets the email of this UserInfo.  # noqa: E501


        :return: The email of this UserInfo.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this UserInfo.


        :param email: The email of this UserInfo.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def first_login(self):
        """Gets the first_login of this UserInfo.  # noqa: E501


        :return: The first_login of this UserInfo.  # noqa: E501
        :rtype: int
        """
        return self._first_login

    @first_login.setter
    def first_login(self, first_login):
        """Sets the first_login of this UserInfo.


        :param first_login: The first_login of this UserInfo.  # noqa: E501
        :type: int
        """

        self._first_login = first_login

    @property
    def funds_available(self):
        """Gets the funds_available of this UserInfo.  # noqa: E501


        :return: The funds_available of this UserInfo.  # noqa: E501
        :rtype: float
        """
        return self._funds_available

    @funds_available.setter
    def funds_available(self, funds_available):
        """Sets the funds_available of this UserInfo.


        :param funds_available: The funds_available of this UserInfo.  # noqa: E501
        :type: float
        """

        self._funds_available = funds_available

    @property
    def id(self):
        """Gets the id of this UserInfo.  # noqa: E501


        :return: The id of this UserInfo.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this UserInfo.


        :param id: The id of this UserInfo.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def investor_id(self):
        """Gets the investor_id of this UserInfo.  # noqa: E501


        :return: The investor_id of this UserInfo.  # noqa: E501
        :rtype: int
        """
        return self._investor_id

    @investor_id.setter
    def investor_id(self, investor_id):
        """Sets the investor_id of this UserInfo.


        :param investor_id: The investor_id of this UserInfo.  # noqa: E501
        :type: int
        """

        self._investor_id = investor_id

    @property
    def language(self):
        """Gets the language of this UserInfo.  # noqa: E501


        :return: The language of this UserInfo.  # noqa: E501
        :rtype: str
        """
        return self._language

    @language.setter
    def language(self, language):
        """Sets the language of this UserInfo.


        :param language: The language of this UserInfo.  # noqa: E501
        :type: str
        """

        self._language = language

    @property
    def name(self):
        """Gets the name of this UserInfo.  # noqa: E501


        :return: The name of this UserInfo.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this UserInfo.


        :param name: The name of this UserInfo.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def surname(self):
        """Gets the surname of this UserInfo.  # noqa: E501


        :return: The surname of this UserInfo.  # noqa: E501
        :rtype: str
        """
        return self._surname

    @surname.setter
    def surname(self, surname):
        """Sets the surname of this UserInfo.


        :param surname: The surname of this UserInfo.  # noqa: E501
        :type: str
        """

        self._surname = surname

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
