# coding: utf-8

"""
    Mobile API

    All decimal values are accepted and returned with 2 decimal place precision, e.g., 150.21. All date fields are sent in ISO 8601 format YYYY-MM-DD, e.g., 2016-11-30.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SellInterest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sell_interest': 'int'
    }

    attribute_map = {
        'sell_interest': 'sell_interest'
    }

    def __init__(self, sell_interest=None):  # noqa: E501
        """SellInterest - a model defined in Swagger"""  # noqa: E501

        self._sell_interest = None
        self.discriminator = None

        if sell_interest is not None:
            self.sell_interest = sell_interest

    @property
    def sell_interest(self):
        """Gets the sell_interest of this SellInterest.  # noqa: E501


        :return: The sell_interest of this SellInterest.  # noqa: E501
        :rtype: int
        """
        return self._sell_interest

    @sell_interest.setter
    def sell_interest(self, sell_interest):
        """Sets the sell_interest of this SellInterest.


        :param sell_interest: The sell_interest of this SellInterest.  # noqa: E501
        :type: int
        """

        self._sell_interest = sell_interest

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SellInterest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SellInterest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
